# Database Connection
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER:flatbudget}
    password: ${POSTGRES_PASS:flatbudget}
    driverClassName: org.postgresql.Driver
  profiles:
    active: dev
  # Hibernate properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: true
  sql:
    init:
      mode: always

flatbudget.app:
  jwtSecret: HRlELXqpSBfe3GdeGegRR
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 86400000
  jwtCookieName: flatbudget-jwt
  jwtRefreshCookieName: flatbudget-jwt-refresh
