okta:
  oauth2:
    issuer: ${issuer}
    audience: ${audience}
    client-secret: ${client_secret}
    client-id: ${client_id}
  auth0:
    mgmt:
      access:
        token: ${mgmt_token}
        audience: ${mgmt_audience}
logging:
  level:
    org:
      springframework:
        web: error

# Database Connection
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER:flatbudget}
    password: ${POSTGRES_PASS:flatbudget}
    driverClassName: org.postgresql.Driver
  profiles:
    active: dev
  # Hibernate properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}