INSERT INTO role(name)
SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT * FROM role WHERE name = 'ROLE_USER');
INSERT INTO role(name)
SELECT 'ROLE_SUPERUSER' WHERE NOT EXISTS (SELECT * FROM role WHERE name = 'ROLE_SUPERUSER');
INSERT INTO role(name)
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT * FROM role WHERE name = 'ROLE_ADMIN');